### ISSUE TITLE
performDismiss() setting incorrect view height

### ISSUE THREAD

**Issue by tikithepug** [brnunes/SwipeableRecyclerView#5]
Hi, I am using your SwipeableRecyclerView in my own side project, and it is very easy to use! So I have to say thank you for creating this.

I have found a small bug, however. When using this code with a RecyclerView that has items of different height, on dismissing either item, the height is set to the original dismissed item's height, when it should be set to the height of the item below it. I will give an example:

Let's say you have 2 items in a list:
(Item 1) Height: 100dp
(Item 2) Height: 60dp

You swipe Item 1 away. So now you should be left with this:
(Item 2) Height: 60dp

Right? But what you end up with is actually this:
(Item 2) Height: 100dp

I believe the culprit is in the method `private void performDismiss(final View dismissView, final int dismissPosition)` at [line 332](https://github.com/brnunes/SwipeableRecyclerView/blob/master/app/src/main/java/brnunes/swipeablecardview/SwipeableRecyclerViewTouchListener.java#L332). I changed it from `lp.height = originalHeight;` to `lp.height = LayoutParams.WRAP_CONTENT;` and it worked as expected. I'm not sure if this is a universal fix or it possibly depends on the height of the view set by the developer in the XML layout file, as I have indeed set it to `WRAP_CONTENT`. If it makes any difference, I am using a `Cardview` with a `RecyclerView`.

Thank you again for this wonderful module!

**Comment by brnunes** [comment]
Hi @mrkhozam, I'm glad this project is being helpful.
Thank you for the input!
You were right on the problem. I think I fixed it.

When a view is dismissed we get its current height to use in the animation, and after the animation ends the `LayoutParams.height` was simply being set to the original height value.

That is a problem when the `LayoutParams.height` was originally `MATCH_PARENT` or `WRAP_CONTENT`. In those cases, we would set the height back to the value calculated for the cell that was just dismissed, instead of setting it back to the original value (`MATCH_PARENT` or `WRAP_CONTENT`). So when the cell was reused, the height would be fixed as the height of the dismissed cell, instead of calculated again for the new content.

[I fixed that](https://github.com/brnunes/SwipeableRecyclerView/commit/0910fa8001141029adae6ae0734ddf04485cc6e3#diff-02a5481496b2a5ee3ce89da31ee8f067) by keeping the original value of the `LayoutParams.height` and setting it back if it was `MATCH_PARENT` or `WRAP_CONTENT`.

Now it should work for both fixed height and `MATCH_PARENT` / `WRAP_CONTENT`.

Thanks again for creating the issue. Let me know if there's still any problem.
All the best!
